#!/usr/bin/env bash

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/.init.sh

###
#
##

# Validation
if [ -z "$1" ]; then
  ERR_CODE=2 error "Missing required parameter: template-dir"
fi

if [ -z "$2" ]; then
  ERR_CODE=2 error "Missing required parameter: output-dir"
fi

TEMPLATE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/"$1"
debug "Template fullpath is $TEMPLATE"

if [ -d "$TEMPLATE" ]; then
  ERR_CODE=3 error "Could not find a template for $1"
fi

debug "Populating $2 from template $1"
mkdir -p "$2"
cp -R "$TEMPLATE"/. "$2"/.

# templates.make
